@echo off

REM Remove *.asv files generated by MATLAB in this directory and all subdirectories.

echo Removing "*.aux" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.aux"') do del "%%i" /f /q
echo.

echo Removing "*.bbl" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.bbl"') do del "%%i" /f /q
echo.

echo Removing "*.blg" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.blg"') do del "%%i" /f /q
echo.

echo Removing "*.log" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.log"') do del "%%i" /f /q
echo.

echo Removing "*.out" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.out"') do del "%%i" /f /q
echo.

echo Removing "*.toc" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.toc"') do del "%%i" /f /q
echo.

echo Removing "*.tps" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.tps"') do del "%%i" /f /q
echo.

echo Removing "*.tex.bak" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.tex.bak"') do del "%%i" /f /q
echo.

echo Removing "*.tex.sav" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.tex.sav"') do del "%%i" /f /q
echo.

echo "%~n0.bat" done.


